// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Video App API
 *
 * ビデオ管理アプリケーションのREST API
 *
 * API version: 1.0.0
 */

package generated

import (
	"context"
	"net/http"
	"os"
	"reflect"
)



// CapturesAPIRouter defines the required methods for binding the api requests to a responses for the CapturesAPI
// The CapturesAPIRouter implementation should parse necessary information from the http request,
// pass the data to a CapturesAPIServicer to perform the required actions, then write the service results to the http response.
type CapturesAPIRouter interface { 
	ApiV1CapturesGet(http.ResponseWriter, *http.Request)
	ApiV1CapturesPost(http.ResponseWriter, *http.Request)
}
// VideosAPIRouter defines the required methods for binding the api requests to a responses for the VideosAPI
// The VideosAPIRouter implementation should parse necessary information from the http request,
// pass the data to a VideosAPIServicer to perform the required actions, then write the service results to the http response.
type VideosAPIRouter interface { 
	ApiV1VideosGet(http.ResponseWriter, *http.Request)
	ApiV1VideosSearchGet(http.ResponseWriter, *http.Request)
	ApiV1VideosIdGet(http.ResponseWriter, *http.Request)
	ApiV1VideosIdDownloadGet(http.ResponseWriter, *http.Request)
	ApiV1VideosIdThumbnailRegeneratePost(http.ResponseWriter, *http.Request)
}


// CapturesAPIServicer defines the api actions for the CapturesAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type CapturesAPIServicer interface { 
	ApiV1CapturesGet(context.Context, int32, int32, int32) (ImplResponse, error)
	ApiV1CapturesPost(context.Context, *os.File, int32) (ImplResponse, error)
}


// VideosAPIServicer defines the api actions for the VideosAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type VideosAPIServicer interface { 
	ApiV1VideosGet(context.Context, []int32, string, int32, int32, string, string) (ImplResponse, error)
	ApiV1VideosSearchGet(context.Context, string, int32, int32, string, string) (ImplResponse, error)
	ApiV1VideosIdGet(context.Context, int32) (ImplResponse, error)
	ApiV1VideosIdDownloadGet(context.Context, int32) (ImplResponse, error)
	ApiV1VideosIdThumbnailRegeneratePost(context.Context, int32, ThumbnailRegenerateRequest) (ImplResponse, error)
}
