// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Video App API
 *
 * ビデオ管理アプリケーションのREST API
 *
 * API version: 1.0.0
 */

package generated

import (
	"net/http"
	"strings"
	"os"
)

// CapturesAPIController binds http requests to an api service and writes the service results to the http response
type CapturesAPIController struct {
	service CapturesAPIServicer
	errorHandler ErrorHandler
}

// CapturesAPIOption for how the controller is set up.
type CapturesAPIOption func(*CapturesAPIController)

// WithCapturesAPIErrorHandler inject ErrorHandler into controller
func WithCapturesAPIErrorHandler(h ErrorHandler) CapturesAPIOption {
	return func(c *CapturesAPIController) {
		c.errorHandler = h
	}
}

// NewCapturesAPIController creates a default api controller
func NewCapturesAPIController(s CapturesAPIServicer, opts ...CapturesAPIOption) *CapturesAPIController {
	controller := &CapturesAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the CapturesAPIController
func (c *CapturesAPIController) Routes() Routes {
	return Routes{
		"ApiV1CapturesGet": Route{
			"ApiV1CapturesGet",
			strings.ToUpper("Get"),
			"/api/v1/captures",
			c.ApiV1CapturesGet,
		},
		"ApiV1CapturesPost": Route{
			"ApiV1CapturesPost",
			strings.ToUpper("Post"),
			"/api/v1/captures",
			c.ApiV1CapturesPost,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the CapturesAPIController
func (c *CapturesAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"ApiV1CapturesGet",
			strings.ToUpper("Get"),
			"/api/v1/captures",
			c.ApiV1CapturesGet,
		},
		Route{
			"ApiV1CapturesPost",
			strings.ToUpper("Post"),
			"/api/v1/captures",
			c.ApiV1CapturesPost,
		},
	}
}



// ApiV1CapturesGet - キャプチャ一覧を取得
func (c *CapturesAPIController) ApiV1CapturesGet(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var videoIdParam int32
	if query.Has("video_id") {
		param, err := parseNumericParameter[int32](
			query.Get("video_id"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "video_id", Err: err}, nil)
			return
		}

		videoIdParam = param
	} else {
	}
	var pageParam int32
	if query.Has("page") {
		param, err := parseNumericParameter[int32](
			query.Get("page"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "page", Err: err}, nil)
			return
		}

		pageParam = param
	} else {
		var param int32 = 1
		pageParam = param
	}
	var limitParam int32
	if query.Has("limit") {
		param, err := parseNumericParameter[int32](
			query.Get("limit"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
			WithMaximum[int32](100),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "limit", Err: err}, nil)
			return
		}

		limitParam = param
	} else {
		var param int32 = 20
		limitParam = param
	}
	result, err := c.service.ApiV1CapturesGet(r.Context(), videoIdParam, pageParam, limitParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ApiV1CapturesPost - キャプチャを作成
func (c *CapturesAPIController) ApiV1CapturesPost(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseMultipartForm(32 << 20); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var fileParam *os.File
	{
		param, err := ReadFormFileToTempFile(r, "file")
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "file", Err: err}, nil)
			return
		}

		fileParam = param
	}
	
	
	
	
	videoIdParam := r.FormValue("video_id")
	result, err := c.service.ApiV1CapturesPost(r.Context(), fileParam, videoIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
