// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Video App API
 *
 * ビデオ管理アプリケーションのREST API
 *
 * API version: 1.0.0
 */

package generated

import (
	"context"
	"net/http"
	"errors"
	"os"
)

// CapturesAPIService is a service that implements the logic for the CapturesAPIServicer
// This service should implement the business logic for every endpoint for the CapturesAPI API.
// Include any external packages or services that will be required by this service.
type CapturesAPIService struct {
}

// NewCapturesAPIService creates a default api service
func NewCapturesAPIService() *CapturesAPIService {
	return &CapturesAPIService{}
}

// ApiV1CapturesGet - キャプチャ一覧を取得
func (s *CapturesAPIService) ApiV1CapturesGet(ctx context.Context, videoId int32, page int32, limit int32) (ImplResponse, error) {
	// TODO - update ApiV1CapturesGet with the required logic for this service method.
	// Add api_captures_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CaptureListResponse{}) or use other options such as http.Ok ...
	// return Response(200, CaptureListResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ApiV1CapturesGet method not implemented")
}

// ApiV1CapturesPost - キャプチャを作成
func (s *CapturesAPIService) ApiV1CapturesPost(ctx context.Context, file *os.File, videoId int32) (ImplResponse, error) {
	// TODO - update ApiV1CapturesPost with the required logic for this service method.
	// Add api_captures_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, Capture{}) or use other options such as http.Ok ...
	// return Response(201, Capture{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ApiV1CapturesPost method not implemented")
}
