// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Video App API
 *
 * ビデオ管理アプリケーションのREST API
 *
 * API version: 1.0.0
 */

package generated

import (
	"context"
	"net/http"
	"errors"
	"reflect"
)

// VideosAPIService is a service that implements the logic for the VideosAPIServicer
// This service should implement the business logic for every endpoint for the VideosAPI API.
// Include any external packages or services that will be required by this service.
type VideosAPIService struct {
}

// NewVideosAPIService creates a default api service
func NewVideosAPIService() *VideosAPIService {
	return &VideosAPIService{}
}

// ApiV1VideosGet - ビデオ一覧を取得
func (s *VideosAPIService) ApiV1VideosGet(ctx context.Context, ids []int32, filterBy string, page int32, limit int32, sort string, order string) (ImplResponse, error) {
	// TODO - update ApiV1VideosGet with the required logic for this service method.
	// Add api_videos_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, VideoListResponse{}) or use other options such as http.Ok ...
	// return Response(200, VideoListResponse{}), nil

	// TODO: Uncomment the next line to return response Response(422, Error{}) or use other options such as http.Ok ...
	// return Response(422, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ApiV1VideosGet method not implemented")
}

// ApiV1VideosSearchGet - ビデオを検索
func (s *VideosAPIService) ApiV1VideosSearchGet(ctx context.Context, q string, page int32, limit int32, order string, filterBy string) (ImplResponse, error) {
	// TODO - update ApiV1VideosSearchGet with the required logic for this service method.
	// Add api_videos_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, VideoListResponse{}) or use other options such as http.Ok ...
	// return Response(200, VideoListResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ApiV1VideosSearchGet method not implemented")
}

// ApiV1VideosIdGet - ビデオ詳細を取得
func (s *VideosAPIService) ApiV1VideosIdGet(ctx context.Context, id int32) (ImplResponse, error) {
	// TODO - update ApiV1VideosIdGet with the required logic for this service method.
	// Add api_videos_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, VideoResponse{}) or use other options such as http.Ok ...
	// return Response(200, VideoResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ApiV1VideosIdGet method not implemented")
}

// ApiV1VideosIdDownloadGet - ビデオをダウンロード
func (s *VideosAPIService) ApiV1VideosIdDownloadGet(ctx context.Context, id int32) (ImplResponse, error) {
	// TODO - update ApiV1VideosIdDownloadGet with the required logic for this service method.
	// Add api_videos_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, *os.File{}) or use other options such as http.Ok ...
	// return Response(200, *os.File{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ApiV1VideosIdDownloadGet method not implemented")
}

// ApiV1VideosIdThumbnailRegeneratePost - サムネイルを再生成
func (s *VideosAPIService) ApiV1VideosIdThumbnailRegeneratePost(ctx context.Context, id int32, body ThumbnailRegenerateRequest) (ImplResponse, error) {
	// TODO - update ApiV1VideosIdThumbnailRegeneratePost with the required logic for this service method.
	// Add api_videos_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ThumbnailRegenerateResponse{}) or use other options such as http.Ok ...
	// return Response(200, ThumbnailRegenerateResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	// return Response(404, Error{}), nil

	// TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	// return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ApiV1VideosIdThumbnailRegeneratePost method not implemented")
}
