// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Video App API
 *
 * ビデオ管理アプリケーションのREST API
 *
 * API version: 1.0.0
 */

package generated

import (
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"strings"
	"reflect"

	"github.com/gorilla/mux"
)

// VideosAPIController binds http requests to an api service and writes the service results to the http response
type VideosAPIController struct {
	service VideosAPIServicer
	errorHandler ErrorHandler
}

// VideosAPIOption for how the controller is set up.
type VideosAPIOption func(*VideosAPIController)

// WithVideosAPIErrorHandler inject ErrorHandler into controller
func WithVideosAPIErrorHandler(h ErrorHandler) VideosAPIOption {
	return func(c *VideosAPIController) {
		c.errorHandler = h
	}
}

// NewVideosAPIController creates a default api controller
func NewVideosAPIController(s VideosAPIServicer, opts ...VideosAPIOption) *VideosAPIController {
	controller := &VideosAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the VideosAPIController
func (c *VideosAPIController) Routes() Routes {
	return Routes{
		"ApiV1VideosGet": Route{
			"ApiV1VideosGet",
			strings.ToUpper("Get"),
			"/api/v1/videos",
			c.ApiV1VideosGet,
		},
		"ApiV1VideosSearchGet": Route{
			"ApiV1VideosSearchGet",
			strings.ToUpper("Get"),
			"/api/v1/videos/search",
			c.ApiV1VideosSearchGet,
		},
		"ApiV1VideosIdGet": Route{
			"ApiV1VideosIdGet",
			strings.ToUpper("Get"),
			"/api/v1/videos/{id}",
			c.ApiV1VideosIdGet,
		},
		"ApiV1VideosIdDownloadGet": Route{
			"ApiV1VideosIdDownloadGet",
			strings.ToUpper("Get"),
			"/api/v1/videos/{id}/download",
			c.ApiV1VideosIdDownloadGet,
		},
		"ApiV1VideosIdThumbnailRegeneratePost": Route{
			"ApiV1VideosIdThumbnailRegeneratePost",
			strings.ToUpper("Post"),
			"/api/v1/videos/{id}/thumbnail/regenerate",
			c.ApiV1VideosIdThumbnailRegeneratePost,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the VideosAPIController
func (c *VideosAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"ApiV1VideosGet",
			strings.ToUpper("Get"),
			"/api/v1/videos",
			c.ApiV1VideosGet,
		},
		Route{
			"ApiV1VideosSearchGet",
			strings.ToUpper("Get"),
			"/api/v1/videos/search",
			c.ApiV1VideosSearchGet,
		},
		Route{
			"ApiV1VideosIdGet",
			strings.ToUpper("Get"),
			"/api/v1/videos/{id}",
			c.ApiV1VideosIdGet,
		},
		Route{
			"ApiV1VideosIdDownloadGet",
			strings.ToUpper("Get"),
			"/api/v1/videos/{id}/download",
			c.ApiV1VideosIdDownloadGet,
		},
		Route{
			"ApiV1VideosIdThumbnailRegeneratePost",
			strings.ToUpper("Post"),
			"/api/v1/videos/{id}/thumbnail/regenerate",
			c.ApiV1VideosIdThumbnailRegeneratePost,
		},
	}
}



// ApiV1VideosGet - ビデオ一覧を取得
func (c *VideosAPIController) ApiV1VideosGet(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	idsParam, err := parseNumericArrayParameter[int32](
		query.Get("ids"), ",", false,
		WithParse[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Param: "ids", Err: err}, nil)
		return
	}
	var filterByParam string
	if query.Has("filterBy") {
		param := query.Get("filterBy")

		filterByParam = param
	} else {
	}
	var pageParam int32
	if query.Has("page") {
		param, err := parseNumericParameter[int32](
			query.Get("page"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "page", Err: err}, nil)
			return
		}

		pageParam = param
	} else {
		var param int32 = 1
		pageParam = param
	}
	var limitParam int32
	if query.Has("limit") {
		param, err := parseNumericParameter[int32](
			query.Get("limit"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
			WithMaximum[int32](100),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "limit", Err: err}, nil)
			return
		}

		limitParam = param
	} else {
		var param int32 = 20
		limitParam = param
	}
	var sortParam string
	if query.Has("sort") {
		param := query.Get("sort")

		sortParam = param
	} else {
		param := "created_at"
		sortParam = param
	}
	var orderParam string
	if query.Has("order") {
		param := query.Get("order")

		orderParam = param
	} else {
		param := "desc"
		orderParam = param
	}
	result, err := c.service.ApiV1VideosGet(r.Context(), idsParam, filterByParam, pageParam, limitParam, sortParam, orderParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ApiV1VideosSearchGet - ビデオを検索
func (c *VideosAPIController) ApiV1VideosSearchGet(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var qParam string
	if query.Has("q") {
		param := query.Get("q")

		qParam = param
	} else {
		c.errorHandler(w, r, &RequiredError{Field: "q"}, nil)
		return
	}
	var pageParam int32
	if query.Has("page") {
		param, err := parseNumericParameter[int32](
			query.Get("page"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "page", Err: err}, nil)
			return
		}

		pageParam = param
	} else {
		var param int32 = 1
		pageParam = param
	}
	var limitParam int32
	if query.Has("limit") {
		param, err := parseNumericParameter[int32](
			query.Get("limit"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
			WithMaximum[int32](100),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "limit", Err: err}, nil)
			return
		}

		limitParam = param
	} else {
		var param int32 = 20
		limitParam = param
	}
	var orderParam string
	if query.Has("order") {
		param := query.Get("order")

		orderParam = param
	} else {
		param := "desc"
		orderParam = param
	}
	var filterByParam string
	if query.Has("filterBy") {
		param := query.Get("filterBy")

		filterByParam = param
	} else {
	}
	result, err := c.service.ApiV1VideosSearchGet(r.Context(), qParam, pageParam, limitParam, orderParam, filterByParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ApiV1VideosIdGet - ビデオ詳細を取得
func (c *VideosAPIController) ApiV1VideosIdGet(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam, err := parseNumericParameter[int32](
		params["id"],
		WithRequire[int32](parseInt32),
		WithMinimum[int32](1),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Param: "id", Err: err}, nil)
		return
	}
	result, err := c.service.ApiV1VideosIdGet(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ApiV1VideosIdDownloadGet - ビデオをダウンロード
func (c *VideosAPIController) ApiV1VideosIdDownloadGet(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam, err := parseNumericParameter[int32](
		params["id"],
		WithRequire[int32](parseInt32),
		WithMinimum[int32](1),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Param: "id", Err: err}, nil)
		return
	}
	result, err := c.service.ApiV1VideosIdDownloadGet(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ApiV1VideosIdThumbnailRegeneratePost - サムネイルを再生成
func (c *VideosAPIController) ApiV1VideosIdThumbnailRegeneratePost(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam, err := parseNumericParameter[int32](
		params["id"],
		WithRequire[int32](parseInt32),
		WithMinimum[int32](1),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Param: "id", Err: err}, nil)
		return
	}
	var bodyParam ThumbnailRegenerateRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&bodyParam); err != nil && !errors.Is(err, io.EOF) {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertThumbnailRegenerateRequestRequired(bodyParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertThumbnailRegenerateRequestConstraints(bodyParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ApiV1VideosIdThumbnailRegeneratePost(r.Context(), idParam, bodyParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
