// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Video App API
 *
 * ビデオ管理アプリケーションのREST API
 *
 * API version: 1.0.0
 */

package generated




type VideoResponse struct {

	// リクエスト成功フラグ
	IsSuccess bool `json:"is_success"`

	// ビデオソース（URL）
	Src string `json:"src"`

	// ビデオタイトル
	Title string `json:"title,omitempty"`

	// ビデオ説明
	Description string `json:"description,omitempty"`

	// 弾幕コメント一覧
	Comments []ApiComment `json:"comments"`
}

// AssertVideoResponseRequired checks if the required fields are not zero-ed
func AssertVideoResponseRequired(obj VideoResponse) error {
	elements := map[string]interface{}{
		"is_success": obj.IsSuccess,
		"src": obj.Src,
		"comments": obj.Comments,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Comments {
		if err := AssertApiCommentRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertVideoResponseConstraints checks if the values respects the defined constraints
func AssertVideoResponseConstraints(obj VideoResponse) error {
	for _, el := range obj.Comments {
		if err := AssertApiCommentConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
