// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Video App API
 *
 * ビデオ管理アプリケーションのREST API
 *
 * API version: 1.0.0
 */

package generated


import (
	"time"
)



type ThumbnailInfo struct {

	// サムネイル幅
	Width int32 `json:"width,omitempty"`

	// サムネイル高さ
	Height int32 `json:"height,omitempty"`

	// 生成日時
	GeneratedAt time.Time `json:"generated_at,omitempty"`
}

// AssertThumbnailInfoRequired checks if the required fields are not zero-ed
func AssertThumbnailInfoRequired(obj ThumbnailInfo) error {
	return nil
}

// AssertThumbnailInfoConstraints checks if the values respects the defined constraints
func AssertThumbnailInfoConstraints(obj ThumbnailInfo) error {
	return nil
}
