// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Video App API
 *
 * ビデオ管理アプリケーションのREST API
 *
 * API version: 1.0.0
 */

package generated




type Pagination struct {

	// 現在のページ番号
	Page int32 `json:"page"`

	// 1ページあたりのアイテム数
	Limit int32 `json:"limit"`

	// 総アイテム数
	Total int32 `json:"total"`

	// 総ページ数
	TotalPages int32 `json:"total_pages"`
}

// AssertPaginationRequired checks if the required fields are not zero-ed
func AssertPaginationRequired(obj Pagination) error {
	elements := map[string]interface{}{
		"page": obj.Page,
		"limit": obj.Limit,
		"total": obj.Total,
		"total_pages": obj.TotalPages,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPaginationConstraints checks if the values respects the defined constraints
func AssertPaginationConstraints(obj Pagination) error {
	return nil
}
