// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Video App API
 *
 * ビデオ管理アプリケーションのREST API
 *
 * API version: 1.0.0
 */

package generated




type ThumbnailRegenerateResponse struct {

	// ビデオID
	Id int32 `json:"id"`

	ThumbnailInfo ThumbnailInfo `json:"thumbnail_info"`

	// ステータスメッセージ
	Message string `json:"message"`
}

// AssertThumbnailRegenerateResponseRequired checks if the required fields are not zero-ed
func AssertThumbnailRegenerateResponseRequired(obj ThumbnailRegenerateResponse) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"thumbnail_info": obj.ThumbnailInfo,
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertThumbnailInfoRequired(obj.ThumbnailInfo); err != nil {
		return err
	}
	return nil
}

// AssertThumbnailRegenerateResponseConstraints checks if the values respects the defined constraints
func AssertThumbnailRegenerateResponseConstraints(obj ThumbnailRegenerateResponse) error {
	if err := AssertThumbnailInfoConstraints(obj.ThumbnailInfo); err != nil {
		return err
	}
	return nil
}
