// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Video App API
 *
 * ビデオ管理アプリケーションのREST API
 *
 * API version: 1.0.0
 */

package generated


import (
	"time"
)



type Video struct {

	// ビデオID
	Id int32 `json:"id"`

	// ファイル名
	FileName string `json:"file_name"`

	// ビデオステータス
	Status string `json:"status,omitempty"`

	// ファイルサイズ（バイト）
	FileSize int32 `json:"file_size"`

	// 実況コメント数
	JikkyoCommentCount int32 `json:"jikkyo_comment_count,omitempty"`

	// 実況日時
	JikkyoDate time.Time `json:"jikkyo_date,omitempty"`

	// 閲覧数
	Views int32 `json:"views"`

	// お気に入りフラグ
	Liked bool `json:"liked"`

	// 動画長（秒）
	Duration float64 `json:"duration"`

	// 作成日時
	CreatedAt time.Time `json:"created_at"`

	// 更新日時
	UpdatedAt time.Time `json:"updated_at"`

	ThumbnailInfo ThumbnailInfo `json:"thumbnail_info,omitempty"`
}

// AssertVideoRequired checks if the required fields are not zero-ed
func AssertVideoRequired(obj Video) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"file_name": obj.FileName,
		"file_size": obj.FileSize,
		"views": obj.Views,
		"liked": obj.Liked,
		"duration": obj.Duration,
		"created_at": obj.CreatedAt,
		"updated_at": obj.UpdatedAt,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertThumbnailInfoRequired(obj.ThumbnailInfo); err != nil {
		return err
	}
	return nil
}

// AssertVideoConstraints checks if the values respects the defined constraints
func AssertVideoConstraints(obj Video) error {
	if err := AssertThumbnailInfoConstraints(obj.ThumbnailInfo); err != nil {
		return err
	}
	return nil
}
