// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Video App API
 *
 * ビデオ管理アプリケーションのREST API
 *
 * API version: 1.0.0
 */

package generated




type CaptureListResponse struct {

	Data []Capture `json:"data"`

	Pagination Pagination `json:"pagination"`
}

// AssertCaptureListResponseRequired checks if the required fields are not zero-ed
func AssertCaptureListResponseRequired(obj CaptureListResponse) error {
	elements := map[string]interface{}{
		"data": obj.Data,
		"pagination": obj.Pagination,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Data {
		if err := AssertCaptureRequired(el); err != nil {
			return err
		}
	}
	if err := AssertPaginationRequired(obj.Pagination); err != nil {
		return err
	}
	return nil
}

// AssertCaptureListResponseConstraints checks if the values respects the defined constraints
func AssertCaptureListResponseConstraints(obj CaptureListResponse) error {
	for _, el := range obj.Data {
		if err := AssertCaptureConstraints(el); err != nil {
			return err
		}
	}
	if err := AssertPaginationConstraints(obj.Pagination); err != nil {
		return err
	}
	return nil
}
