// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Video App API
 *
 * ビデオ管理アプリケーションのREST API
 *
 * API version: 1.0.0
 */

package generated




type ApiComment struct {

	// コメント時刻（秒）
	Time float32 `json:"time"`

	// コメント表示位置
	Type string `json:"type"`

	// コメントサイズ
	Size string `json:"size"`

	// コメント色
	Color string `json:"color"`

	// コメント作成者
	Author string `json:"author,omitempty"`

	// コメント本文
	Text string `json:"text"`
}

// AssertApiCommentRequired checks if the required fields are not zero-ed
func AssertApiCommentRequired(obj ApiComment) error {
	elements := map[string]interface{}{
		"time": obj.Time,
		"type": obj.Type,
		"size": obj.Size,
		"color": obj.Color,
		"text": obj.Text,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertApiCommentConstraints checks if the values respects the defined constraints
func AssertApiCommentConstraints(obj ApiComment) error {
	return nil
}
