// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Video App API
 *
 * ビデオ管理アプリケーションのREST API
 *
 * API version: 1.0.0
 */

package generated


import (
	"time"
)



type Capture struct {

	// キャプチャID
	Id int32 `json:"id"`

	// ファイル名
	Filename string `json:"filename"`

	// 作成日時
	CreatedAt time.Time `json:"created_at"`

	// ビデオID（外部キー）
	VideoId int32 `json:"video_id"`
}

// AssertCaptureRequired checks if the required fields are not zero-ed
func AssertCaptureRequired(obj Capture) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"filename": obj.Filename,
		"created_at": obj.CreatedAt,
		"video_id": obj.VideoId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCaptureConstraints checks if the values respects the defined constraints
func AssertCaptureConstraints(obj Capture) error {
	return nil
}
