// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Video App API
 *
 * ビデオ管理アプリケーションのREST API
 *
 * API version: 1.0.0
 */

package generated


import (
	"errors"
)



type ThumbnailRegenerateRequest struct {

	// サムネイル幅
	Width int32 `json:"width,omitempty"`

	// サムネイル高さ
	Height int32 `json:"height,omitempty"`

	// 抽出タイムスタンプ（秒）
	Timestamp float32 `json:"timestamp,omitempty"`
}

// AssertThumbnailRegenerateRequestRequired checks if the required fields are not zero-ed
func AssertThumbnailRegenerateRequestRequired(obj ThumbnailRegenerateRequest) error {
	return nil
}

// AssertThumbnailRegenerateRequestConstraints checks if the values respects the defined constraints
func AssertThumbnailRegenerateRequestConstraints(obj ThumbnailRegenerateRequest) error {
	if obj.Width < 1 {
		return &ParsingError{Param: "Width", Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.Height < 1 {
		return &ParsingError{Param: "Height", Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.Timestamp < 0 {
		return &ParsingError{Param: "Timestamp", Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
